APPLICATION = driver_bme280_saul
include ../Makefile.tests_common

USEMODULE += bme280
USEMODULE += saul_reg
USEMODULE += saul_default
USEMODULE += auto_init_saul
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
